# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HumonoidRobotControl(object):
    def setupUi(self, HumonoidRobotControl):
        HumonoidRobotControl.setObjectName("HumonoidRobotControl")
        HumonoidRobotControl.resize(829, 711)
        self.centralwidget = QtWidgets.QWidget(HumonoidRobotControl)
        self.centralwidget.setStyleSheet("#DownSide{\n"
" background-color: rgb(45, 91, 104);\n"
"}\n"
"#UpUp{\n"
" background-color:rgb(47, 91, 104);\n"
"}\n"
"\n"
"#UpSide{\n"
" background-color: rgb(255, 255, 255);\n"
"}\n"
"#MiddleLeft{\n"
" background-color: rgb(45, 91, 104);\n"
"}\n"
"#MiddleRight{\n"
" background-color: rgb(45, 91, 104);\n"
"}\n"
"\n"
"#Status{\n"
" background-color: rgb(255, 255, 0);\n"
"}\n"
"#MiddleDown{\n"
"    background-color: rgb(47, 91, 104);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.UpSide = QtWidgets.QWidget(self.centralwidget)
        self.UpSide.setGeometry(QtCore.QRect(0, -10, 831, 551))
        self.UpSide.setObjectName("UpSide")
        self.UpMiddle = QtWidgets.QWidget(self.UpSide)
        self.UpMiddle.setGeometry(QtCore.QRect(0, 50, 831, 501))
        self.UpMiddle.setObjectName("UpMiddle")
        self.MiddleLeft = QtWidgets.QWidget(self.UpMiddle)
        self.MiddleLeft.setGeometry(QtCore.QRect(0, 0, 20, 501))
        self.MiddleLeft.setObjectName("MiddleLeft")
        self.Middle = QtWidgets.QWidget(self.UpMiddle)
        self.Middle.setGeometry(QtCore.QRect(20, 20, 791, 441))
        self.Middle.setObjectName("Middle")
        self.FeedLabel = QtWidgets.QLabel(self.Middle)
        self.FeedLabel.setGeometry(QtCore.QRect(0, 0, 791, 441))
        self.FeedLabel.setText("")
        self.FeedLabel.setObjectName("FeedLabel")
        self.MiddleRight = QtWidgets.QWidget(self.UpMiddle)
        self.MiddleRight.setGeometry(QtCore.QRect(810, 0, 20, 501))
        self.MiddleRight.setObjectName("MiddleRight")
        self.MiddleDown = QtWidgets.QWidget(self.UpMiddle)
        self.MiddleDown.setGeometry(QtCore.QRect(0, 460, 827, 41))
        self.MiddleDown.setObjectName("MiddleDown")
        self.Status = QtWidgets.QWidget(self.MiddleDown)
        self.Status.setGeometry(QtCore.QRect(90, 0, 641, 41))
        self.Status.setObjectName("Status")
        self.statusText = QtWidgets.QLineEdit(self.Status)
        self.statusText.setGeometry(QtCore.QRect(0, 5, 641, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.statusText.setFont(font)
        self.statusText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statusText.setReadOnly(True)
        self.statusText.setObjectName("statusText")
        self.UpUp = QtWidgets.QWidget(self.UpSide)
        self.UpUp.setGeometry(QtCore.QRect(0, 10, 831, 61))
        self.UpUp.setObjectName("UpUp")
        self.Title = QtWidgets.QLineEdit(self.UpUp)
        self.Title.setGeometry(QtCore.QRect(120, 15, 591, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setAutoFillBackground(False)
        self.Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Title.setReadOnly(True)
        self.Title.setObjectName("Title")
        self.DownSide = QtWidgets.QWidget(self.centralwidget)
        self.DownSide.setGeometry(QtCore.QRect(0, 540, 831, 171))
        self.DownSide.setObjectName("DownSide")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.DownSide)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MODE = QtWidgets.QWidget(self.DownSide)
        self.MODE.setObjectName("MODE")
        self.MODE_2 = QtWidgets.QLineEdit(self.MODE)
        self.MODE_2.setGeometry(QtCore.QRect(30, 10, 261, 31))
        self.MODE_2.setAutoFillBackground(False)
        self.MODE_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MODE_2.setReadOnly(True)
        self.MODE_2.setObjectName("MODE_2")
        self.buttonCONTRASTING = QtWidgets.QRadioButton(self.MODE)
        self.buttonCONTRASTING.setGeometry(QtCore.QRect(30, 50, 161, 21))
        self.buttonCONTRASTING.setChecked(False)
        self.buttonCONTRASTING.setObjectName("buttonCONTRASTING")
        self.modeGroup = QtWidgets.QButtonGroup(HumonoidRobotControl)
        self.modeGroup.setObjectName("modeGroup")
        self.modeGroup.addButton(self.buttonCONTRASTING)
        self.buttonMIRRORING = QtWidgets.QRadioButton(self.MODE)
        self.buttonMIRRORING.setGeometry(QtCore.QRect(210, 80, 151, 21))
        self.buttonMIRRORING.setChecked(True)
        self.buttonMIRRORING.setObjectName("buttonMIRRORING")
        self.modeGroup.addButton(self.buttonMIRRORING)
        self.buttonAMPLIFYING = QtWidgets.QRadioButton(self.MODE)
        self.buttonAMPLIFYING.setGeometry(QtCore.QRect(30, 80, 161, 21))
        self.buttonAMPLIFYING.setChecked(False)
        self.buttonAMPLIFYING.setObjectName("buttonAMPLIFYING")
        self.modeGroup.addButton(self.buttonAMPLIFYING)
        self.buttonRMIRRORING = QtWidgets.QRadioButton(self.MODE)
        self.buttonRMIRRORING.setGeometry(QtCore.QRect(210, 50, 161, 21))
        self.buttonRMIRRORING.setChecked(False)
        self.buttonRMIRRORING.setObjectName("buttonRMIRRORING")
        self.modeGroup.addButton(self.buttonRMIRRORING)
        self.ScreenSettings = QtWidgets.QWidget(self.MODE)
        self.ScreenSettings.setGeometry(QtCore.QRect(382, 10, 431, 113))
        self.ScreenSettings.setObjectName("ScreenSettings")
        self.ScreenSettingsText = QtWidgets.QLineEdit(self.ScreenSettings)
        self.ScreenSettingsText.setGeometry(QtCore.QRect(120, 0, 261, 31))
        self.ScreenSettingsText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ScreenSettingsText.setReadOnly(True)
        self.ScreenSettingsText.setObjectName("ScreenSettingsText")
        self.BlackBackground = QtWidgets.QCheckBox(self.ScreenSettings)
        self.BlackBackground.setGeometry(QtCore.QRect(120, 50, 131, 21))
        self.BlackBackground.setChecked(False)
        self.BlackBackground.setObjectName("BlackBackground")
        self.HeadInfo = QtWidgets.QCheckBox(self.ScreenSettings)
        self.HeadInfo.setGeometry(QtCore.QRect(290, 50, 69, 18))
        self.HeadInfo.setChecked(True)
        self.HeadInfo.setObjectName("HeadInfo")
        self.HideModes = QtWidgets.QCheckBox(self.ScreenSettings)
        self.HideModes.setEnabled(True)
        self.HideModes.setGeometry(QtCore.QRect(290, 80, 121, 21))
        self.HideModes.setChecked(False)
        self.HideModes.setObjectName("HideModes")
        self.UpperBodyInfo = QtWidgets.QCheckBox(self.ScreenSettings)
        self.UpperBodyInfo.setGeometry(QtCore.QRect(120, 80, 131, 21))
        self.UpperBodyInfo.setChecked(True)
        self.UpperBodyInfo.setObjectName("UpperBodyInfo")
        self.sliderStrength = QtWidgets.QSlider(self.MODE)
        self.sliderStrength.setEnabled(False)
        self.sliderStrength.setGeometry(QtCore.QRect(30, 110, 111, 16))
        self.sliderStrength.setMinimum(1)
        self.sliderStrength.setMaximum(10)
        self.sliderStrength.setProperty("value", 5)
        self.sliderStrength.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.sliderStrength.setObjectName("sliderStrength")
        self.labelStrengthValue = QtWidgets.QLabel(self.MODE)
        self.labelStrengthValue.setGeometry(QtCore.QRect(150, 110, 30, 20))
        self.labelStrengthValue.setObjectName("labelStrengthValue")
        self.buttonAUTOMATIC = QtWidgets.QRadioButton(self.MODE)
        self.buttonAUTOMATIC.setGeometry(QtCore.QRect(210, 110, 80, 18))
        self.buttonAUTOMATIC.setObjectName("buttonAUTOMATIC")
        self.modeGroup.addButton(self.buttonAUTOMATIC)
        self.buttonRANDOM = QtWidgets.QRadioButton(self.MODE)
        self.buttonRANDOM.setGeometry(QtCore.QRect(300, 110, 80, 18))
        self.buttonRANDOM.setObjectName("buttonRANDOM")
        self.modeGroup.addButton(self.buttonRANDOM)
        self.overlay = QtWidgets.QLabel(self.MODE)
        self.overlay.setEnabled(True)
        self.overlay.setGeometry(QtCore.QRect(-4, 3, 411, 131))
        self.overlay.setStyleSheet("background-color: rgb(47, 91, 104);")
        self.overlay.setText("")
        self.overlay.setObjectName("overlay")
        self.horizontalLayout.addWidget(self.MODE)
        HumonoidRobotControl.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(HumonoidRobotControl)
        self.statusBar.setObjectName("statusBar")
        HumonoidRobotControl.setStatusBar(self.statusBar)

        self.retranslateUi(HumonoidRobotControl)
        QtCore.QMetaObject.connectSlotsByName(HumonoidRobotControl)

    def retranslateUi(self, HumonoidRobotControl):
        _translate = QtCore.QCoreApplication.translate
        HumonoidRobotControl.setWindowTitle(_translate("HumonoidRobotControl", "MainWindow"))
        self.statusText.setPlaceholderText(_translate("HumonoidRobotControl", "Status"))
        self.Title.setText(_translate("HumonoidRobotControl", "Agent Control Via 2D Camera"))
        self.MODE_2.setText(_translate("HumonoidRobotControl", "MODE"))
        self.buttonCONTRASTING.setText(_translate("HumonoidRobotControl", "CONTRASTING"))
        self.buttonMIRRORING.setText(_translate("HumonoidRobotControl", "MIRRORING"))
        self.buttonAMPLIFYING.setText(_translate("HumonoidRobotControl", "AMPLIFYING"))
        self.buttonRMIRRORING.setText(_translate("HumonoidRobotControl", "REVERSED MIRRORING"))
        self.ScreenSettingsText.setText(_translate("HumonoidRobotControl", "Screen Settings"))
        self.BlackBackground.setText(_translate("HumonoidRobotControl", "Black Background"))
        self.HeadInfo.setText(_translate("HumonoidRobotControl", "Head Info"))
        self.HideModes.setText(_translate("HumonoidRobotControl", "Hide Modes"))
        self.UpperBodyInfo.setText(_translate("HumonoidRobotControl", "Upper Body Info"))
        self.labelStrengthValue.setText(_translate("HumonoidRobotControl", "VALUE"))
        self.buttonAUTOMATIC.setText(_translate("HumonoidRobotControl", "AUTO"))
        self.buttonRANDOM.setText(_translate("HumonoidRobotControl", "RANDOM"))
